In [357]:
import numpy as np
starCluster = np.array([[1, 2, 3], [5, 7, 9], [2, 4, 6], [7, 7, 7]])
def oddBrightness(array):
    oddArray = np.empty((0, array.shape[1]), dtype=int)
    for list in array:
        oddCount = 0
        evenCount = 0
        for number in list:
            if number % 2 == 1:
                oddCount += 1
            else:
                evenCount += 1
            if oddCount == 3:
                oddArray = np.vstack([oddArray, list])
    return oddArray
    
oddBrightness(starCluster)

array([[5, 7, 9],
       [7, 7, 7]])

In [359]:
def createCheckerboard():
    checkerboard = np.zeros((8, 8), dtype=int)
    return checkerboard

createCheckerboard()

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [361]:
checkerboard = createCheckerboard()
def oddRow(checkerboard):
    for row in range(0, len(checkerboard)):
        if row % 2 == 0:
            for index, number in enumerate(checkerboard[row]):
                if index % 2 == 0:
                    checkerboard[row][index] = 1
    return checkerboard

oddRow(checkerboard)

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [363]:
checkerboard = createCheckerboard()
oddRowCheckerboard = oddRow(checkerboard)
def evenRow(checkerboard):
    for row in range(0, len(checkerboard)):
        if row % 2 == 1:
            for index, number in enumerate(checkerboard[row]):
                if index % 2 == 1:
                    checkerboard[row][index] = 1
    return checkerboard

evenRow(oddRowCheckerboard)

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [365]:
checkerboard = createCheckerboard()
def reverseBoard(checkerboard):
    for row in range(0, len(checkerboard)):
        if row % 2 == 0:
            for index, number in enumerate(checkerboard[row]):
                if index % 2 == 1:
                    checkerboard[row][index] = 1
    for row in range(0, len(checkerboard)):
        if row % 2 == 1:
            for index, number in enumerate(checkerboard[row]):
                if index % 2 == 0:
                    checkerboard[row][index] = 1
    return checkerboard

reverseBoard(checkerboard)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [373]:
def expandingGalaxy(array, separation):
    newArray = np.empty(0)
    separationString = " "*separation
    
    for string in array:
        newString = string[0]
        for letters in string[1:]:
            newString += separationString + letters
        newArray = np.append(newArray, newString)
    return newArray

universe = np.array(["galaxy", "black hole"])
expandingGalaxy(universe, 1)

array(['g a l a x y', 'b l a c k   h o l e'], dtype='<U32')

In [375]:
def secondBiggest():
    array = np.random.randint(100, 1000, (5, 5))
    newArray = np.empty(0, dtype=int)
    print(array)
    print(array.T)
    
    for row in array.T:
        biggestNumber = 0
        for number in row:
            if number >= biggestNumber:
                biggestNumber = number
        newArray = np.append(newArray, biggestNumber)
    
    return newArray
    
secondBiggest()

[[271 319 257 576 145]
 [472 617 198 991 844]
 [136 379 448 596 401]
 [280 706 198 799 215]
 [290 352 260 355 422]]
[[271 472 136 280 290]
 [319 617 379 706 352]
 [257 198 448 198 260]
 [576 991 596 799 355]
 [145 844 401 215 422]]


array([472, 706, 448, 991, 844])